#pragma once

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_END };


enum OBJID { OBJ_PLAYER, OBJ_BULLET, OBJ_FWMONSTER, OBJ_DFMONSTER, OBJ_CHMONSTER, OBJ_MOUSE, OBJ_END };

enum MOBTYPE { MOB_DF, MOB_FW,MOB_CH, MOB_END };

